### PR TITLE
Redraw mask element on each dispatchDraw

### PR DESCRIPTION
**Pull request by johgusta**
# Summary
I ran into the same issues as some others with an animated `maskElement` on Android, 
https://github.com/react-native-community/react-native-masked-view/issues/22. The bitmap used for masking was drawn on layout, and then cached for future drawing. I changed this to always draw the mask element before applying the mask on the underlying view. 

I am far from an expert on Android development and this might be a bad pattern, but redrawing the bitmap for the mask element on each drawing cycle seems to be performant for me.  

### What's required for testing (prerequisites)?
Use an `Animated.View` as a mask element.

### What are the steps to reproduce (after prerequisites)?
Perform an animation and see that the mask is applied correctly

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |

## Checklist

- [x ] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by crutchcorn** [comment]
I've tested this on my instance as well, can confirm that it works well! Thanks so much!

**Comment by AlexandrePalo** [comment]
Do you have any snack example ?
I'm still not able to animate correctly a mask in Android after the merge :(

**Comment by wcandillon** [comment]
This seems to fix #22, is it confirmed?

**Comment by crutchcorn** [comment]
@wcandillion it absolutely has.

**Pull request merged**
